### ISSUE TITLE
Comments in OLApproachSupport/OLModulations/ ....

### ISSUE THREAD

**Issue by DavidBrainard** [DavidBrainard/OneLightToolbox#4]
OLCalculateStartsStopsModulation
OLReceptorIsolateMakeModulationStartsStops

Note that parameters are defined in default routine at the end of OLModualationParamsDictionary.

**Comment by spitschan** [comment]
After commenting an outdated version of both files, I tried to commit and push and noticed that I didn't have the most up-to-date function. I took a look at the most recent version and many comments that I made were already figured out by you. I've added a high level comment in a783948. Can you please point me out which pieces exactly need commenting?

**Comment by DavidBrainard** [comment]
Ah, the issue was posted before we went through those functions late last week and figured them out.
I should have made a note here after we had done that.  I think we are good -- we simplified the code somewhat as we went through as well.  I think we are good on these two.  Sorry for the extra work, it didn't occur to me that you might work on it without pulling ....

Closing this one.
